# DROP DATABASE if exists test;
CREATE DATABASE if not exists test DEFAULT CHARACTER SET 'UTF8';
# CREATE DATABASE test DEFAULT CHARACTER SET 'UTF8';
USE test;
DROP TABLE IF EXISTS user;
CREATE TABLE user(
 id INT NOT NULL AUTO_INCREMENT KEY,
 username VARCHAR(20) NOT NULL UNIQUE,
 password TEXT NOT NULL,
 public ENUM("T","F") DEFAULT "T",
 see INT DEFAULT 0,
 create_time DATETIME DEFAULT NOW()
)ENGINE=INNODB CHARSET=UTF8;

DROP TABLE IF EXISTS video_info;
CREATE TABLE video_info(
 id VARCHAR(64) NOT NULL PRIMARY KEY,
 author_id INT,
 name TEXT,
 display_ctime TEXT,
 public ENUM("T","F") DEFAULT "T" ,
 see INT DEFAULT 0,
 create_time DATETIME DEFAULT NOW()
)ENGINE=INNODB CHARSET=UTF8;

DROP TABLE IF EXISTS comments;
CREATE TABLE comment(
 id VARCHAR(64) NOT NULL PRIMARY KEY,
 video_id VARCHAR(64),
 author_id INT,
 content TEXT,
 public ENUM("T","F") DEFAULT "T",
 c_time DATETIME DEFAULT NOW(),
 see INT DEFAULT 0 comment
)ENGINE=INNODB CHARSET=UTF8;

DROP TABLE IF EXISTS product;
CREATE TABLE product(
 id VARCHAR(64) NOT NULL PRIMARY KEY,
 name VARCHAR(20) NOT NULL comment,
 description VARCHAR(50) NOT NULL,
 price DOUBLE DEFAULT 0 comment,
 public ENUM("T","F") DEFAULT "T",
 see INT DEFAULT 0,
 createTime DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB CHARSET=UTF8;